# gitshop:order-template
name: "\U0001F6D2 Place an Order"
description: Order products from our store
title: "[ORDER] "
labels: ["gitshop:order", "gitshop:status:pending-payment"]
body:
    - type: markdown
      attributes:
        value: |
            ## Welcome to our store!
            Fill out the form below to place your order. You'll receive a payment link after submitting.
    - type: dropdown
      id: product
      attributes:
        label: Product
        description: Select the product you want to order
        options:
            - Coffee Blend V1 — $16.00 (SKU:COFFEE_BLEND_V1)
      validations:
        required: true
    - type: dropdown
      id: quantity
      attributes:
        label: Quantity
        options:
            - "1"
            - "2"
            - "3"
            - "4"
            - "5"
      validations:
        required: true
    - type: dropdown
      id: grind
      attributes:
        label: Grind
        options:
            - Ground
            - Whole Bean
      validations:
        required: true
    - type: input
      attributes:
        label: Notes
        description: Any notes you may have about your order
